#Due to GitHub awkwardness, it's not easy to reduce the review requirement for collaborators.
#Our policy is that 2 collaborators should be aware of every change.
#For outside PRs, this means 2 collaborator reviews.
#For PRs made by collaborators, this means 1 reviewer + the author.
#We trust that collaborators don't need as much oversight.
name: Auto approve collaborator PRs

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Auto-approve disabled"
